### ISSUE TITLE
CSS Model mangles animation sequence using keyframes 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1091]
The dojox mobile themes contain animation sequence [keyframes](https://developer.mozilla.org/en/css/css_animations)

``` css
.mblScaleIn.mblIn {
    z-index : 0;
    -webkit-animation-duration : .5s;
    -webkit-animation-name : mblScaleInIn;
    -webkit-animation-timing-function : ease-out;
}
.dj_android .mblScaleIn.mblIn {
    -webkit-animation-name : mblScaleInInAndroid;
}
@-webkit-keyframes mblScaleInOut {
    from { -webkit-transform: scale(1.0); }
    to { -webkit-transform: scale(1.0); }
}
@-webkit-keyframes mblScaleInIn {
    from {
        -webkit-transform: scale(0.0);
        opacity: 0;
    }
    to {
        -webkit-transform: scale(1.0);
        opacity: 1;
    }
}
@-webkit-keyframes mblScaleInInAndroid {
    from { -webkit-transform: scale(0.0); }
    to { -webkit-transform: scale(1.0); }
}
```

When a css rule is change in the file and the file is save the output css is corrupted.
The output key rule looks something like:

``` css
@ -webkit-keyframesmblScaleInOut{from{-webkit-transform:scale(1.0);to {
    -webkit-transform : scale(1.0);
}
```

To recreate:
1) checkout the mobileThemeEditor branch
2)Create a new theme, called a1 (clone android theme).
3) Click on the header widget and change the background-color
4) Save the theme
5) close the theme editor
6) reopen your theme, notice that the buttons are the wrong size.

If you now look at the a1.css and search for '@', noticed that the syntax is bad

**Comment by waynevicknair** [comment]
fixed with commit 9dd0ff35c9

**Comment by billreed63** [comment]
I am still seeing a problem,
on the master branch..

1) Clone the android theme (a1)
2) In theme editor select the view and change the background color
3) Save the theme

In the users work space look at the a1.css file all the @keyframes... are gone and at the bottom of the file I see

@ undefined

**Comment by waynevicknair** [comment]
weird. bill, can you test it with this small test case:
@-webkit-keyframes mblScaleInOut {
    from { -webkit-transform: scale(1.0); }
    to   { -webkit-transform: scale(1.0); }
}

@-webkit-keyframes mblScaleInIn {
    from {
        -webkit-transform: scale(0.0);
        opacity: 0;
    }
    to {
        -webkit-transform: scale(1.0);
        opacity: 1;
    }
}

@-webkit-keyframes mblScaleInInAndroid {
    from { -webkit-transform: scale(0.0); }
    to { -webkit-transform: scale(1.0); }
}

i pasted those rules in the CSS editor and saved. then i edited (i.e. changed indentation and line returns) and saved. then i closed and reopened. everything was OK. the i added this rule at the bottom of the file:

#foo { color: red; }

then saved, closed and reopened. still everything fine.

if that works for you then it means i didn't code for all the cases in the larger a1.css you are using. if that doesn't work for you, we need to look at your environment.

**Comment by waynevicknair** [comment]
yep. i didn't code for the nn% case.

**Comment by waynevicknair** [comment]
i think i got it with this commit 6918681a63
