### ISSUE TITLE
New File dialog with folder selected in Files shows nothing in Where field

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1466]
1. Create new folder.
2. Select that folder in the Files view.
3. Click on New HTML Page icon.

New HTML Page dialog appears with the **Where** drop down showing nothing.  When clicking on the drop down, there is no menu (doesn't even show `(root)`.

**Comment by JonFerraiolo** [comment]
I just pulled down today's build and repeated the above steps with Mac/Chrome and I'm seeing "folder1" as the value for the Where drop down. What browser? Running a daily build or off of Eclipse? What were you doing earlier in the session?

**Comment by JonFerraiolo** [comment]
And what specific action did you use to create the new folder? Context menu in Files palette?

**Comment by jhpedemonte** [comment]
OK, got it:
1. Create new folder 'aaa'.
2. Select folder in Files view.
3. Click on New HTML Page icon.  Notice that 'aaa' is shown in **Where** text field, and clicking on drop down shows both 'aaa' and '(root)'.
4. Cancel new file dialog.
5. Delete 'aaa' folder.
6. Click on New HTML Page icon.

**Where** textfield shows nothing and clicking on it doesn't even show '(root)'.

**Comment by jhpedemonte** [comment]
If there isn't a quick fix for this, I'm fine with pushing off to M5.

**Comment by JonFerraiolo** [comment]
Let's leave it on M4 for a bit longer to investigate. This might be related to other resource bugs (see #1455 and #1440).

**Comment by JonFerraiolo** [comment]
@childsb 

I believe the problem with @jhpedemonte's scenario is that the New File dialog asks Runtime.js what's the current selection in the Files palette, and Runtime.js still thinks (even after deletion) the currently selected resource is folder aaa because the selection list in Runtime doesn't get updated after the deleteResource operation. The logic in Runtime for keeping track of selection is misguided. Instead, we should just query the Tree widget in the Explorer palette to figure out what the current selection is because that Tree widget manages what the user sees in terms of which file/folder is currently selected.

**Comment by JonFerraiolo** [comment]
Fixed by @childsb fix: 4173656028af8cdede97a814ddd0b28a5c0cc027

**Comment by jhpedemonte** [comment]
Still not fixed.  Following Eclipse Project test:
1. Create new project with Eclipse support.
2. When maqetta reloads, select (but don't open) the **WebContent** folder.  Right click and select **New Folder**.  Enter "aaa" for folder name and click "OK".
3. Open the **WebContent** folder, which shows contents including "aaa".  Select "aaa" folder.  New HTML Page.

Notice that the New File dialog's **Where** drop down is blank.

Tested with Safari, on both macwayne2 and lab9:50020.
