### ISSUE TITLE
Absolute positioning drag/drop goes to wrong location with scrollbar

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#147]
@JonFerraiolo reports:
- New HTML file
- Click on flow-vs-absolute position icon on toolbar and go into absolute
  positioning
- Drag/drop a Calendar somewhere towards the top/left of the canvas

Result=> Calendar jumps down and to the right

If you just go into absolute mode and drop widgets,
no problem. But if you put a tall ContentPane at the bottom of the canvas to
make the rendered page taller than the canvas area and therefore force a
scrollbar to appear, and then scroll the page vertically, and then drop a
widget in absolute mode, then a new widget will down to the wrong position.
(It's almost as if the scroll distance is added twice.)

**Comment by waynevicknair** [comment]
I encountered this bug while testing VE part2 today in Safari 5.0.5.

**Comment by JonFerraiolo** [comment]
Pushed to M3, but I think this is fixed. Adam, could you please try on Safari 5.1, Chrome and FF4 (or greater), and if you can't reproduce, please close.

**Comment by peller** [comment]
The first part seems to be a dup of #824.  The scrolling bug still exists.
