### ISSUE TITLE
Theme Editor subwidget menu exception

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2905]
1) Clone claro
2) open debugger, set pause on uncaught exceptions
3) Select Calendar widget
4) move mouse over subwidget list

Note the following exception:
72
Uncaught TypeError: Cannot read property 'domNode' of undefined _CssStateMixin.js:272
handler _CssStateMixin.js:272

**Comment by JonFerraiolo** [comment]
I see why this regressed. It has to do with putting the various property sections inside of a TabContainer. Those changes modified the logic regarding which pane of the properties palette was active. Still working on a fix, though.

**Comment by JonFerraiolo** [comment]
@billreed63: When you "set pause on uncaught exceptions", and then select Calendar, is it necessary to go through a large number of uncaught exceptions in the parser before reaching the real error?

**Comment by billreed63** [comment]
No, I just get the one. But in chrome I have the purple not the blue pause on errors on

**Comment by JonFerraiolo** [comment]
I'm not getting an exception using last night's daily build even though I have Win/FF set to break on all errors, but I am seeing messages in the console. The messages in the console reflect a bug that I fixed earlier today with 6f7aaf9d. 

So, there is a good chance I have fixed this issue, but leaving this open for now, waiting for tomorrow's build to see if the console messages go away.

**Comment by JonFerraiolo** [comment]
I tested on last night's build and can't reproduce. 

@billreed63: sending this issue to you for you to test and see if the problem has gone away. If so, please close.

**Comment by billreed63** [comment]
still seeing the error on my development environment on chrome/win 7 but I do not see it on http://maqetta-app-test.austin.ibm.com/maqetta/ 
Seems very strange to see it development version but not on the built version. Must be some thing in my enviroment
