### ISSUE TITLE
device silhouette not being displayed after file save/reopen

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3031]
Create a iphone html file
DnD and header
Save and close
Reopen

The device is none.
I have seen this on FF and Chrome

**Comment by peller** [comment]
can't reproduce this now.  Could have been fixed by d323e84d35da0eb1a1ca245ee0b16e9d02551203?

**Comment by JonFerraiolo** [comment]
I'm still seeing this when running from Eclipse using Mac/Chrome, pulling latest code from a few hours ago, which is after the above commit.

**Comment by billreed63** [comment]
The root cause of this issue is issue #2808, once that issue is fixed this issue will be resolved.

**Comment by billreed63** [comment]
Seems to have been fixed by f60a6c3
