### ISSUE TITLE
Dojo Web Builder fails on Maqetta.org

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3522]
@peller 

I had previously opened #3387. That one was closed over my vacation, but I see then that  @JonFerraiolo followed up with #3465 when he couldn't verify #3387. #3465 was opened on an internal server, and it looks like @peller's response was that DWB on that machine needed to be updated.

So, I don't know if I should be reopening #3387 or attaching to something else. But, I just tried on maqetta.org and it failed.

There was no indication of an error on the client. And, I ssh'ed to the server and tried to look at the log using previous instructions from @jhpedemonte , but running the following command returned nothing:

```
tail /var/log/nginx/app.maqetta.org_error.log
```

But, the download occurs pretty fast and when looking at dojo.js in the zip file, its size is only 156 KB. So, it definitely didn't work.

I had been counting on this being fixed in M7.0.1 for my Developer Works article(s). So, disappointed to see not working after  #3387 was closed. So, hoping maybe just a matter of DWB needing to be updated on maqetta.org as well?

**Comment by aerwin** [comment]
@peller 

Well, maybe error isn't on our end... I entered the URL to my app at http://build.dojotoolkit.org/ and it fails there too. But, there's no indication what failed... just a message that quickly flashes that "something went wrong."

Here's the URL to my app:

http://app.maqetta.org/maqetta/user/G/ws/workspace/weightControlPrototype20121005/index.html

I suppose as slow as the server is nowadays it could be timing out or something?

**Comment by peller** [comment]
There have been a number of regressions on the DWB server side, perhaps more on our side masked by them once we work through.

To start, the "dwb" source library, requested in the source code analyze step from the Maqetta Download command, no longer exists.  @jthomas suggested we remove this going forward.  He tried putting it back on the server, but then we ran into a 202 error code when Maqetta was only expecting a 200, so it seems we may not be able to get the deployed Maqetta/DWB combination to work.  These two simple changes may get us working again in 7.0.2

**Comment by peller** [comment]
As for uploading the workplace.zip directly to build.dojotoolkit.org (taking Maqetta out of the loop) that also seems to fail, but for different reasons.  @jthomas is investigating, but says it may be part of a larger AMD refactor going on, so we may have to tell our users they have to wait for this.

**Comment by aerwin** [comment]
Thanks, @peller ...

Do you know if going to http://build.dojotoolkit.org/  and putting in the URL to a Maqetta page  (e.g., http://app.maqetta.org/maqetta/user/G/ws/workspace/weightControlPrototype20121005/index.html ) is equivalent to uploading workspace.zip? E.g., is the failure I see doing that the same as what @jthomas found with workspace.zip?

> so we may have to tell our users they have to wait for this.

I know our support within Maqetta is experimental, but is http://build.dojotoolkit.org/  considered experimental as well? E.g., it used to work to put in the URL to a Maqetta page.

**Comment by peller** [comment]
On Thu, Oct 11, 2012 at 2:11 PM, aerwin notifications@github.com wrote:

> Do you know if going to http://build.dojotoolkit.org/ and putting in the
> URL to a Maqetta page (e.g.,
> http://app.maqetta.org/maqetta/user/G/ws/workspace/weightControlPrototype20121005/index.html) is equivalent to uploading workspace.zip? E.g., is the failure I see
> doing that the same as what @jthomas https://github.com/jthomas found
> with workspace.zip?
> 
> Different, I think.  The URL path could work.  Have you tried it?  Only
> question is how well it would handle the maqetta/\* references. Yesterday, I
> wasn't able to get it to respond at all to a maqetta.org URL (even though
> maqetta.org seemed responsive enough).  This morning, I got the full list
> of dependencies, but didn't try going further.  I can try this again this
> afternoon.
> 
>  so we may have to tell our users they have to wait for this.
> 
> I know our support within Maqetta is experimental, but is
> http://build.dojotoolkit.org/ considered experimental as well? E.g., it
> used to work to put in the URL to a Maqetta page.
> 
> It's best-effort, open source.  James is doing it in his free time, as far
> as I know.  Even as an IBM employee, that's no guarantee.  Another caveat
> is that it's running on an Amazon web service.  James says not to expect
> much in terms of performance, and it the service starts getting hammered by
> multiple users, there's no telling what could happen...  The good news is
> that it's reasonably intelligent about caching.

-Adam

**Comment by aerwin** [comment]
> The URL path could work.  Have you tried it? 

Yes, I reported it failed the day I opened the problem report. And, it looks like it's still failing.

**Comment by peller** [comment]
Oh, sorry, I thought you meant you were uploading the zip.

Uploading the url worked for me this morning, I swear.  Now the build.dojotoolkit.org app comes up with an error even before I send my test app:

```
Error
arguments: undefined
get stack: function () { [native code] }
message: "dojox.data.AndOrReadStore:  The json data provided by the creation arguments is malformed.  Items within the list have identifier: [name].  Value collided: [dijit.BackgroundIframe]"
set stack: function () { [native code] }
type: undefined
__proto__: d
```

after sending a url to a preview in maqetta, I get something similar:

```
Error
arguments: undefined
get stack: function () { [native code] }
message: "dojox.data.AndOrReadStore: Invalid item argument."
set stack: function () { [native code] }
type: undefined
__proto__: d
 dojo.js:14
(anonymous function) dojo.js:14
reject.errback dojo.js:14
_100 dojo.js:14
_fe dojo.js:14
reject.errback dojo.js:14
_100 dojo.js:14
_fe dojo.js:14
resolve.callback dojo.js:14
_100 dojo.js:14
_fe dojo.js:14
resolve.callback dojo.js:14
(anonymous function) dwb.js:14
func dojo.js:14
_27d
```

**Comment by peller** [comment]
@jthomas

**Comment by jthomas** [comment]
I accidentally broke the host last night while trying to fix the "dwb" package that Maqetta relies on. I've fixed this now, thanks for spotting! 

Don't use the archive upload, it's not working correctly and the page analysis API should be the one we want. Looking at the sample page given: 
http://app.maqetta.org/maqetta/user/QM/ws/workspace/DynamicDB/file11.html

It's running into issues because that page references built layer files, the auto-analysis feature was orginally intended for use with unoptimised applications. It is getting confused when it tries to recursively analyse built layers since the module source for dependencies is inlined. 

I've just tried a fix to ensure it doesn't descend into built layer files and hopefully this should fix the issue. Maqetta seems to have gone down just now, I'll have to wait until it's back to confirm.

**Comment by jthomas** [comment]
Okay, it's back up now....

That fix works and I can now analyse the URL above correctly. I've pushed the change to the remote host and redeployed. We should be good from now on....

**Comment by aerwin** [comment]
Hi, @jthomas ...

I just tried my URL again ( http://app.maqetta.org/maqetta/user/G/ws/workspace/weightControlPrototype20121005/index.html ), and I still see the flicker of this message.... any ideas?

![GitHub Logo](http://i.imgur.com/SAkpZ.png)

**Comment by peller** [comment]
When I try @aerwin 's url, I see this on the analyze step:

/api/dependencies: 400 Bad Request

`{"error":"Unable to parse URL parameter for remote Web Application. Check format of the request parameter value"}`

payload looks ok to me:

```
------WebKitFormBoundaryihJBddcfzDcjTXn4
Content-Disposition: form-data; name="value"

http://app.maqetta.org/maqetta/user/G/ws/workspace/weightControlPrototype20121005/index.html
------WebKitFormBoundaryihJBddcfzDcjTXn4
Content-Disposition: form-data; name="type"

URL
------WebKitFormBoundaryihJBddcfzDcjTXn4--
```

The 400 comes back in about 3 seconds.  I do see that the page is _very_ slow to load right now from a clear cache (> 1 min), but I do not know if that's the issue.

**Comment by jthomas** [comment]
That URL was tripping the (fairly conservative) HTTP timeout limits. I've upped the limit for the connection from 3 seconds to 30, which should help in general. 

However, loading the page in my browser takes a huge amount of time due to latency, Chrome's telling me "4.3 minutes" for all resources, with some files having nearly two minutes of latency. This will still trip over the increased HTTP limit as it stands.

**Comment by peller** [comment]
Seems to work fine now directly from build.dojotoolkit.org, though it takes a few minutes for the initial build.  see #3879. 

Need to retest this on M10.
